// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARMqIfBBB6dDbGYUtA-Ql8fHOc3qQmgP4',
    appId: '1:690417649301:web:82c7aa4e37cfad14e4fd9c',
    messagingSenderId: '690417649301',
    projectId: 'carrs-dc60d',
    authDomain: 'carrs-dc60d.firebaseapp.com',
    storageBucket: 'carrs-dc60d.firebasestorage.app',
    measurementId: 'G-M89CQSZ9JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGVOj2XX9W0BRX2FP6QtSjMLqKplbsIzo',
    appId: '1:690417649301:android:e6defa84ccf1d0ade4fd9c',
    messagingSenderId: '690417649301',
    projectId: 'carrs-dc60d',
    storageBucket: 'carrs-dc60d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5EywvH284llAVvLTtpDmHR_3ESZ_MGM0',
    appId: '1:690417649301:ios:4cbb03c5963b500ae4fd9c',
    messagingSenderId: '690417649301',
    projectId: 'carrs-dc60d',
    storageBucket: 'carrs-dc60d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAppvv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5EywvH284llAVvLTtpDmHR_3ESZ_MGM0',
    appId: '1:690417649301:ios:4cbb03c5963b500ae4fd9c',
    messagingSenderId: '690417649301',
    projectId: 'carrs-dc60d',
    storageBucket: 'carrs-dc60d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAppvv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARMqIfBBB6dDbGYUtA-Ql8fHOc3qQmgP4',
    appId: '1:690417649301:web:2c37382fe1c9cf9ee4fd9c',
    messagingSenderId: '690417649301',
    projectId: 'carrs-dc60d',
    authDomain: 'carrs-dc60d.firebaseapp.com',
    storageBucket: 'carrs-dc60d.firebasestorage.app',
    measurementId: 'G-7W3TF95V6D',
  );
}
